spring:
    application:
        name: TASI_Dividens
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/dividend_db}
#        url: ${DB_URL:jdbc:postgresql://postgres:5432/dividend_db}  # postgres is the service name in docker-compose
        username: ${DB_USERNAME:db}
        password: ${DB_PASSWORD:1234}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

server:
    port: 8080

dividends:
    job:
        cron: ${DIVIDENDS_JOB_CRON:0 */5 * * * *}
