spring:
    application:
        name: TASI_Dividens
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/dividend_db}
#        url: ${DB_URL:jdbc:postgresql://postgres:5432/dividend_db}  # postgres is the service name in docker-compose
        username: ${DB_USERNAME:db}
        password: ${DB_PASSWORD:1234}
        driver-class-name: org.postgresql.Driver


    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
logging:
    level:
        org:
            springframework:
                web:
                    client=DEBUG:
        java:
            net:
                http=DEBUG:
server:
    port: 8080

dividends:
    job:
        cron: ${DIVIDENDS_JOB_CRON:0 */5 * * * *}

notifications:
    job:
        cron: ${NOTIFICATIONS_JOB_CRON:0 0 7 * * *}
#  prod:  0 0 7 * * *

apple:
    url: https://api.push.apple.com/3/device/
#    url: https://api.sandbox.push.apple.com/3/device/

apns:
     key: ${key}
     key-id: ${key-id}
     team-id: ${team-id}
