name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: 'personal-projects-456515'
  REGION: 'me-central1'
  SERVICE: 'dividens-api'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/460632706650/locations/global/workloadIdentityPools/github/providers/LulwahAlmisfer/TASI_Dividens'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/460632706650/locations/global/workloadIdentityPools/github/providers/LulwahAlmisfer/TASI_Dividens'


      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="me-central1-docker.pkg.dev/personal-projects-456515/dividens-api:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
      - name: 'Deploy to Cloud Run'

        # END - Docker auth and build

        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: 'dividens-api'
          region: 'me-central1'
          # NOTE: If using a pre-built image, update the image name below:

          image: 'me-central1-docker.pkg.dev/personal-projects-456515/dividens-api:${{ github.sha }}'
      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |2-

          echo ${{ steps.deploy.outputs.url }}
